= Rust Strings, Explained
:hp-tags: rust

== Introduction to &str and String

Rust has two main types of strings: `&str` and `String`.

[code,rust]
----
use std::net::TcpStream;

let addr = "127.0.0.1"; // this is a &str, a &'static str to be specific
let mut addr_str = slice.to_string(); // this is a String
let addr2 = &slice; // coerce back to a &str

TcpStream::connect(addr); // no problem
TcpStream::connect(&*addr_string); // no automatic coercion to traits of &str
----

This string `addr`, also known as a 'string slice', is statically allocated, meaning that it’s saved inside our compiled program, and exists for the entire duration it runs. The greeting binding is a reference to this statically allocated string. String slices have a fixed size, and cannot be mutated.

A `String` like `addr_str`, on the other hand, is a heap-allocated string. This string is growable, and is also guaranteed to be UTF-8. Strings are commonly created by converting from a string slice using the `to_string` method.

To coerce a `String` into a `&str`, you can use `&`, unless the destination type is a trait of &str, in which case you need to use `&*`.


== Should I use a String, a &str, or one of the traits of &str?

Naturally, be as specific as possible when choosing between `&str` or one of the traits of `&str`.  The stdlib example above from link:https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.connect[TcpStream::connect] is a great example

When choosing between `&str` and `String`, choose `&str` **virtually every time**.  Viewing a String as a &str is cheap, but converting the &str to a String involves allocating memory. No reason to do that unless you have to!

If you are coming from a JVM-based language, actively fight the urge to write to `String` types.

This choice preference should apply to both struct and function definitions.

== Concatentation

You can concatenate a &str to the end of a String.  Using what we have learned about moving between the two types, we arrive at these three examples:

[code,rust]
----
let hello = "Hello ".to_string();
let world = "world!";
let hello_world = hello + world;
----

[code,rust]
----
let hello = "Hello ".to_string();
let world = "world!".to_string();
let hello_world = hello + &world; // first coerce world to a &str
----

[code,rust]
----
let hello = "Hello ".to_string();
let world = "world!";
let hello_world = &(hello + &world); // coerce the result to a &'static str
----

== Splitting and destructuring

Suppose we have some simple data structure, like this one representing a Maven-style  dependency.  There is no substitute for reading the whole section on link:https://doc.rust-lang.org/book/lifetimes.html[Lifetimes] for what is going on with this `'a` stuff.

[code,rust]
----
struct Dependency<'a> {
    org: &'a str,
    name: &'a str,
    rev: &'a str
}
----

The current state of populating a simple data structure with pieces of a String is less than ideal.  So let's see the best case pattern now and also what we can do with nightly Rust.  First, today's best case scenario:

[code,rust]
----
fn parse_dependency(dep: &str) -> Result<Dependency, String> {
    let dp = dep.split(':').collect::<Vec<&str>>(); // wince
    return match dp.len() {
        3 => Ok(Dependency { org: dp[0], name: dp[1], rev: dp[2] }),
        _ => Err("--dependency must be in the format org:name:rev".to_string())
    };
}

----

`dep.split(':')` returns a link:https://doc.rust-lang.org/std/str/struct.Split.html[std::str::Split], which implements Iterator, so why the collect acrobatics?  Fundamentally, accessing an Iterator's elements happens with `next()`, but that mutates the underlying Iterator.  Even though we know the subsequent match step will not refer to or rely on `dp` in any way, Rust (understandably) does not allow us to 'move' a value that is being used to evaluate subsequent match statements. 

Unfortunately, `collect()` returns a link:https://doc.rust-lang.org/std/iter/trait.FromIterator.html[std:iter::FromIterator], which by itself has no useful methods.  We have to just **know** that the underlying implementor is link:https://doc.rust-lang.org/collections/vec/struct.Vec.html[collections::Vec], and as uncomfortable as this kind of manual type coercion might be, it seems very unlikely to change.

What about the better way, the way of the future?  It involves an unstable feature called link:https://doc.rust-lang.org/book/slice-patterns.html[Slice Patterns].

[code,rust]
----
#![feature(slice_patterns)]

fn parse_dependency(dep: &str) -> Result<Dependency, &str> {
    return match dep.split(':') {
        [org,name,rev] => Ok(Dependency { org: org, name: name, rev: rev }),
        _ => Err("--dependency must be in the format org:name:rev")
    }
}
----