= Kotlin Testing Framework
:hp-tags: kotlin

This serves as a rough design document for a Kotlin-based specification framework.  The goal is to provide a rich testing framework unifying beneficial concepts from both Spock and Jasmine.  Spek serves as a good working start for providing an idiomatic Kotlin framework.

== Lifecycle Hooks

Take Spek's concept of `beforeOn` and `afterOn` and generalize it to simply `after` and `before` and allow them to be executed at any scope (e.g. given, on, and it).  A given-scoped `after` is roughly equivalent to JUnit's `@AfterClass` and a on-scoped `after` is roughly equivalent to JUnit's `@After`.  There is no corollary to an it-scoped given in JUnit, though there is in Jasmine.

== Diagrammed Assertions

Based on its similar type system, Pieter Niederwieser's link:https://github.com/pniederw/expecty[Expecty] Scala implementation of diagrammed assertions should provide an adequate set of hints as to how to accomplish this in Kotlin.  

== Implicit Assertions

Expecty also contains implicit assertions, but accomplishes it with Scala macros.  We could look for the presence of a certain function invocation, e.g. `it`, use ASM to inject an `assertTrue` diagrammed assertion around each of the statements contained in its `It.() -> Unit` parameter.

== Data Tables

TBD

== Parameterized Test Names

TBD

== Mocking

TBD